#lang racket/base
;; Bootstrap loop. Within a single invocation:
;;   1. Read templates.dat to get current library.
;;   2. Build cover, score.
;;   3. Propose candidate templates from singleton residual.
;;   4. Try each candidate in rank order; accept first that lowers DL.
;;   5. If accepted, repeat from step 2 (the just-added template
;;      changes the singleton residual, opening new patterns).
;;   6. When no candidate improves DL, stop.
;;   7. Write the extended library to templates.dat AND emit
;;      library.rkt — a Racket source file with one macro per
;;      accepted template. The Racket program now contains a literal
;;      definition of every template it has discovered about itself.

(require racket/cmdline racket/file racket/list racket/format)
(require "dot.rkt" "graph.rkt" "grammar.rkt" "score.rkt"
         "recognise.rkt" "propose.rkt" "canonical.rkt"
         "compile.rkt")

(define lib-path "templates.dat")
(define rkt-path "library.rkt")
(define max-size (make-parameter 5))

(define dot-path
  (command-line #:program "bootstrap"
                #:once-each
                [("--max-size") n "Largest template size to consider"
                                (max-size (string->number n))]
                #:args (path) path))

(define (read-library)
  (cond [(file-exists? lib-path)
         (with-input-from-file lib-path read)]
        [else '()]))

(define (write-library lib)
  (call-with-output-file lib-path #:exists 'replace
    (lambda (out) (write lib out) (newline out))))

(define (cover-dl G cover)
  (hash-ref (principled-dl G (grammar-from-cover G cover)) 'total-dl))

(define (string-join strs sep)
  (cond [(null? strs) ""]
        [(null? (cdr strs)) (car strs)]
        [else
         (apply string-append
                (car strs)
                (for/list ([s (in-list (cdr strs))])
                  (string-append sep s)))]))

(define (emit-library-source library dl)
  ;; Write a real Racket source file containing one macro per template.
  ;; The macro for template `R<i>` accepts n-interior named arguments
  ;; and, when expanded, returns the list of edge-pairs the template
  ;; produces among them. This is the program's own description of
  ;; itself — it grows by one definition every iteration.
  (define header
    (string-append
     "#lang racket/base\n"
     ";; AUTO-GENERATED by bootstrap.rkt — do not hand-edit.\n"
     ";; Each successful proposal appends a (define-syntax-rule R<n> ...)\n"
     ";; binding to this file. The library is the program's evolving\n"
     ";; theory of its own input graph.\n"
     "(provide (all-defined-out))\n\n"
     (format ";; Library size: ~a templates, current cover DL=~a bits.\n\n"
             (length library)
             (real->decimal-string dl 1))))
  (define defs
    (for/list ([t (in-list library)] [i (in-naturals)])
      (define n (car t))
      (define edges (cadr t))
      (define args
        (string-join
         (for/list ([k (in-range n)]) (format "n~a" k))
         " "))
      (define edge-forms
        (string-join
         (for/list ([e (in-list edges)])
           (format "(cons n~a n~a)" (car e) (cdr e)))
         " "))
      ;; Procedures (not syntax-rules) so reflective-recognise.rkt can
      ;; apply them at runtime via dynamic-require.
      (format "(define (R~a ~a)\n  (list ~a))\n"
              i args edge-forms)))
  (define text (apply string-append header defs))
  (call-with-output-file rkt-path #:exists 'replace
    (lambda (out) (display text out))))

(define G (load-dot dot-path))
(define library (read-library))
(printf "loaded ~a: ~a nodes, ~a edges; library has ~a templates~n"
        dot-path (graph-n-nodes G) (graph-n-edges G) (length library))

(let outer ([library library] [round 0] [accepted 0])
  (define cover (recognise-cover G library))
  (define dl (cover-dl G cover))
  (printf "~nround ~a: ~a templates, ~a instances, DL=~a~n"
          round (length library) (length cover)
          (real->decimal-string dl 1))
  (define cands (propose-templates G cover library #:max-size (max-size)))
  (printf "  ~a novel candidates~n" (length cands))
  (let try-each ([cs cands])
    (cond
      [(null? cs)
       (printf "  no candidate improved DL; stopping~n")
       (write-library library)
       (emit-library-source library dl)
       (printf "~nfinal: ~a templates, DL=~a; templates.dat + library.rkt updated; ~a accepted this run~n"
               (length library)
               (real->decimal-string dl 1)
               accepted)]
      [else
       (define t (car cs))
       (define trial-lib (append library (list t)))
       (define trial-cover (recognise-cover G trial-lib))
       (define trial-dl (cover-dl G trial-cover))
       (cond
         [(< trial-dl dl)
          (printf "  ACCEPT ~v: ~a → ~a (Δ~a)~n"
                  t
                  (real->decimal-string dl 1)
                  (real->decimal-string trial-dl 1)
                  (real->decimal-string (- trial-dl dl) 1))
          (outer trial-lib (+ round 1) (+ accepted 1))]
         [else
          (try-each (cdr cs))])])))

;; --- in-memory reflection demo ----------------------------------
;; Build runnable procedures from the final library WITHOUT touching
;; disk: each template's s-expression is eval'd in a fresh namespace
;; and stored as a (name . procedure) pair. Apply each procedure to
;; integer ghost-args to recover its edge list — the same reflection
;; pattern as expand.rkt, but the source never hits the filesystem.
(printf "~n--- in-memory eval demo ---~n")
(define final-library (read-library))
(define compiled (compile-templates final-library))
(printf "compiled ~a templates in a fresh namespace (no file involved):~n"
        (length compiled))
(for ([entry (in-list compiled)])
  (define name (car entry))
  (define proc (cdr entry))
  (define recovered (apply-template-to-ghosts proc))
  (printf "  ~a (arity ~a) → ~v~n" name (car recovered) (cadr recovered)))
