#lang racket/base
;; AUTO-GENERATED by bootstrap.rkt — do not hand-edit.
;; Each successful proposal appends a (define-syntax-rule R<n> ...)
;; binding to this file. The library is the program's evolving
;; theory of its own input graph.
(provide (all-defined-out))

;; Library size: 3 templates, current cover DL=697.0 bits.

(define (R0 n0 n1)
  (list (cons n0 n1)))
(define (R1 n0 n1 n2)
  (list (cons n0 n1) (cons n0 n2)))
(define (R2 n0 n1 n2 n3)
  (list (cons n0 n1) (cons n0 n2) (cons n0 n3)))
